services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    depends_on:
      - mariadb
      - cig_backoffice
      - cig_request
      - cig_kitchen
      - spark
    networks:
      - app_net

  cig_backoffice:
    build:
      context: .
      dockerfile: ./cig_backoffice/Dockerfile
    container_name: cig_backoffice
    restart: always
    depends_on:
      - mariadb
    networks:
      - app_net
  
  cig_request:
    build:
      context: .
      dockerfile: ./cig_request/Dockerfile
    container_name: cig_request
    restart: always
    depends_on:
      - mariadb
    networks:
      - app_net

  cig_kitchen:
    build:
      context: .
      dockerfile: ./cig_kitchen/Dockerfile
    container_name: cig_kitchen
    restart: always
    depends_on:
      - mariadb
    networks:
      - app_net

  spark:
    build:
      context: .
      dockerfile: ./spark/Dockerfile
    container_name: spark
    restart: always
    depends_on:
      - mariadb
    networks:
      - app_net

  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=db_cig_burger
      - MARIADB_ROOT_PASSWORD=TRGFgjyiDxlkKU1bpf8vmxmgS9oBvaSw
      - MARIADB_USER=user_db_cig_burger
      - MARIADB_PASSWORD=ren7hICOqosAqu8Es7wagIjuD6KI4o
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    depends_on:
      - mariadb
    networks:
      - app_net

networks:
  app_net:
    driver: bridge